Replace PNG images with SVG icons
GetStream/react-activity-feed pull request #152
Opened 2021-02-23 17:09 UTC by arnautov-anton

2021-02-23 19:00 UTC, mahboubii requested changes
placeholder.png file also should be replaced

2021-02-23 19:00 UTC, mahboubii commented on src/components/RepostButton.js
> +
```suggestion
```

2021-02-23 21:08 UTC, arnautov-anton commented on src/assets/icons.tsx
> +      fill="currentColor"
CanIUse [says](https://caniuse.com/?search=currentColor) it is. :)

2021-02-24 07:24 UTC, mahboubii commented on src/assets/icons.tsx
> +      fill="currentColor"
nice

2021-02-24 07:30 UTC, mahboubii commented on src/components/icons.tsx
> +    viewBox="0 0 512 512"
same for other Icons to allow overriding the default  attributes
```suggestion
    className="raf-reaction-icon__image"
    data-icon="thumbs-up"
    role="img"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 512 512"
     {...props}
```

2021-02-24 07:30 UTC, mahboubii commented on src/components/icons.tsx
> +type Icon = SVGProps<SVGSVGElement>;
```suggestion
type IconProps = SVGProps<SVGSVGElement>;
```

2021-02-24 07:30 UTC, mahboubii commented on src/components/icons.tsx
> +export const ThumbsUpIcon = (props: Icon): JSX.Element => (
no need to specefically set the return type
```suggestion
export const ThumbsUpIcon = (props: IconProps) => (
```

2021-02-24 15:45 UTC, merged